# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reinautils',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/reinautils',
                'lib_path': 'reinautils'},
  'syms': {'reinautils.core': {'reinautils.core.foo': ('core.html#foo', 'reinautils/core.py')}}}
