# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reinautils',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/reinautils',
                'lib_path': 'reinautils'},
  'syms': { 'reinautils.core': { 'reinautils.core.Parameters': ('parameters.html#parameters', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__call__': ('parameters.html#parameters.__call__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__delitem__': ('parameters.html#parameters.__delitem__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__getitem__': ('parameters.html#parameters.__getitem__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__init__': ('parameters.html#parameters.__init__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__len__': ('parameters.html#parameters.__len__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__repr__': ('parameters.html#parameters.__repr__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__setitem__': ('parameters.html#parameters.__setitem__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__str__': ('parameters.html#parameters.__str__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.add_attr': ('parameters.html#parameters.add_attr', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.from_json': ('parameters.html#parameters.from_json', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.to_dict': ('parameters.html#parameters.to_dict', 'reinautils/core.py')}}}
