# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reinautils',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/reinautils',
                'lib_path': 'reinautils'},
  'syms': { 'reinautils.core': { 'reinautils.core.Parameters': ('core.html#parameters', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__call__': ('core.html#parameters.__call__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__delitem__': ('core.html#parameters.__delitem__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__getitem__': ('core.html#parameters.__getitem__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__init__': ('core.html#parameters.__init__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__len__': ('core.html#parameters.__len__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__repr__': ('core.html#parameters.__repr__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__setitem__': ('core.html#parameters.__setitem__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.__str__': ('core.html#parameters.__str__', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.add_attr': ('core.html#parameters.add_attr', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.from_json': ('core.html#parameters.from_json', 'reinautils/core.py'),
                                 'reinautils.core.Parameters.to_dict': ('core.html#parameters.to_dict', 'reinautils/core.py')}}}
